### ISSUE TITLE
Не работают кастомные стили для страниц

### ISSUE THREAD

**Issue by Kanorto** [maposia/remnawave-telegram-sub-mini-app#24]
Вот такая конфигурация не работается и выдается стандартная страница. Очень хотелось бы получить свою страницу из https://github.com/legiz-ru/my-remnawave/blob/main/sub-page/customweb/clash-sing/index.html подобия. 
```
services:
   remnawave-mini-app:
      image: ghcr.io/maposia/remnawave-telegram-sub-mini-app:latest
      container_name: remnawave-telegram-mini-app
      hostname: remnawave-telegram-mini-app
      env_file:
         - .env
      restart: always
      volumes:
        - ./index.html:/opt/app/frontend/index.html
        - ./assets:/opt/app/frontend/assets
        # - ./app-config.json:/app/public/assets/app-config.json
      ports:
         - '0.0.0.0:3020:3020'
      networks:
         - remnawave-network

networks:
   remnawave-network:
        name: remnawave-network
        driver: bridge
        external: true
```
